# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "q2JIldpEgDbLb+R8IBpw/ubRVw487zWFm9j2b+EaVWLJGVDw9z4FaV1vo9wMVBfl4BGmkIddD343XQeQtMgJPwQBoZjnTzs3WSDFCbW7SmnUuFdonKWmKy0tFEp1zfpWvIgqqmkfUSaF8+TPDGMSRUfP+KHhHkIjtKZjiETL+p8Qkdb1OiHtJNtou0oV/ZSt7OyiplPc3smzaVQaNDim6EkXn+73FksDMmt+alacEL4od4qIwzQ/IxRbWgphEB7B3U36DDOZpRQuwrsYv3/e/l+4TylRrbCK8+uTV7+UOHO0TnrhUqm4aeQMVt584bSFDwdVHpUT29dFeESQ7369dAqPfsatjs5LBJBRmckUnXgW0b/tNDvq3i3rIcPWxQovI9OiZuiNkGUvy3rZ/rS6h6ceEW7ojWgd5aIkWiSZErYCUa3SfidpX9Vjm1Zb6oilfvGbWbXjn0gwyE9uUAPYNbVBRWAKVpU8DXVJ/qzAVHpMgVNnLADbarB89O0rB7ykJv8fNLDKMuFQBMRZez/r4EBcmyrkqzvTqlJjZN2tLHrNNMSDXn0sMxv4IPYe5VxXaUCxLNIvShIN+J0ei+0HpUIswS1ECT1+/9XsDgb8Oh56kDubbin+DE9PbNvghp89tNVxuRt51CuXKqgZ9OKfUjuZA9b1+HNH4b0cZ6uTNJg="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
