travis:
  secure:
    BINSTAR_TOKEN: q2JIldpEgDbLb+R8IBpw/ubRVw487zWFm9j2b+EaVWLJGVDw9z4FaV1vo9wMVBfl4BGmkIddD343XQeQtMgJPwQBoZjnTzs3WSDFCbW7SmnUuFdonKWmKy0tFEp1zfpWvIgqqmkfUSaF8+TPDGMSRUfP+KHhHkIjtKZjiETL+p8Qkdb1OiHtJNtou0oV/ZSt7OyiplPc3smzaVQaNDim6EkXn+73FksDMmt+alacEL4od4qIwzQ/IxRbWgphEB7B3U36DDOZpRQuwrsYv3/e/l+4TylRrbCK8+uTV7+UOHO0TnrhUqm4aeQMVt584bSFDwdVHpUT29dFeESQ7369dAqPfsatjs5LBJBRmckUnXgW0b/tNDvq3i3rIcPWxQovI9OiZuiNkGUvy3rZ/rS6h6ceEW7ojWgd5aIkWiSZErYCUa3SfidpX9Vjm1Zb6oilfvGbWbXjn0gwyE9uUAPYNbVBRWAKVpU8DXVJ/qzAVHpMgVNnLADbarB89O0rB7ykJv8fNLDKMuFQBMRZez/r4EBcmyrkqzvTqlJjZN2tLHrNNMSDXn0sMxv4IPYe5VxXaUCxLNIvShIN+J0ei+0HpUIswS1ECT1+/9XsDgb8Oh56kDubbin+DE9PbNvghp89tNVxuRt51CuXKqgZ9OKfUjuZA9b1+HNH4b0cZ6uTNJg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
